export const CREATE_TUTORIAL = 'CREATE_TUTORIAL';
export const RETRIEVE_TUTORIALS = 'RETRIEVE_TUTORIALS';
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL';
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
export const DELETE_ALL_TUTORIALS = 'DELETE_ALL_TUTORIALS';

export const ADD_CARGO = 'ADD_CARGO';
export const REMOVE_CARGO = 'REMOVE_CARGO';

export const ADD_SUB = 'ADD_SUB';
export const REMOVE_SUB = 'REMOVE_SUB';
